[id]
name = "archlinux"
label = "Arch Linux"
type = "linux-live"

[match]
filename_contains = ["archlinux", "x86_64"]

[boot]
kernel = "/mounts/archlinux/arch/boot/x86_64/vmlinuz-linux"
initrd = "/mounts/archlinux/arch/boot/x86_64/initramfs-linux.img"
args = [
  "archiso_http_srv=${boot-url}/mounts/archlinux/",
  "cow_spacesize=1G"
]
