[id]
name = "debian"
label = "Debian Installer"
type = "linux-installer"

[match]
filename_contains = ["debian", "netinst"]

[boot]
kernel = "/mounts/debian/install.amd/vmlinuz"
initrd = "/mounts/debian/install.amd/initrd.gz"
args = [
  "auto=false",
  "priority=low"
]
