[id]
name = "systemrescue"
label = "SystemRescue"
type = "linux-live"

[match]
filename_contains = ["systemrescue", "sysresccd"]

[boot]
kernel = "/mounts/systemrescue/sysresccd/boot/x86_64/vmlinuz"
initrd = "/mounts/systemrescue/sysresccd/boot/x86_64/sysresccd.img"
args = [
  "archisobasedir=sysresccd",
  "archiso_http_srv=${boot-url}/mounts/systemrescue/"
]
